name: Daily build

# Controls when the action will run.
on: 
  schedule:
    - cron: '30 2 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v2

            # Build the ballerina project
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      build -c ./sns
              env:
                ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                REGION: ${{ secrets.REGION }}

            # Send notification when build fails
            - name: Notify failure
              if: ${{ failure() }}
              run: |
                curl \
                -X POST 'https://chat.googleapis.com/v1/spaces/${{secrets.BALLERINA_CHAT_ID}}/messages?key=${{secrets.BALLERINA_CHAT_KEY}}&token=${{secrets.BALLERINA_CHAT_TOKEN}}' \
                --header 'Content-Type: application/json' \
                -d '{"text": "*module-ballerinax-aws.sns* daily build failure \nPlease visit <https://github.com/ballerina-platform/module-ballerinax-aws.sns/actions/workflows/daily-build.yml|the daily build page> for more information"}'
                curl \
                -X POST 'https://chat.googleapis.com/v1/spaces/${{secrets.CONNECTOR_CHAT_ID}}/messages?key=${{secrets.CONNECTOR_CHAT_KEY}}&token=${{secrets.CONNECTOR_CHAT_TOKEN}}' \
                --header 'Content-Type: application/json' \
                -d '{"text": "*module-ballerinax-aws.sns* daily build failure \nPlease visit <https://github.com/ballerina-platform/module-ballerinax-aws.sns/actions/workflows/daily-build.yml|the daily build page> for more information"}'
